# ============================================================
# 🕹️ RETRO PIXEL LED LITE - CONFIGURACION v3.1.0
# ============================================================
# Nota: No dejes espacios alrededor del símbolo '='.
# Ejemplo correcto: BRIGHTNESS=40

[WIFI_NTP]
# Configura tu red WiFi
WIFI_ENABLE=1
SSID=Nombre_De_Tu_Red
PASS=Password_De_Tu_Red
# Configura tu zona horaria
TZ=CET-1CEST,M3.5.0,M10.5.0/3

[HARDWARE]
# Numero de paneles
PANEL_CHAIN=2
# Orden de colores del Panel: RGB, RBG o GBR
COLOR_ORDER=RGB
# Brillo (0 a 255)
BRIGHTNESS=38
# Velocidad I2S: 0=8MHz, 1=10MHz, 2=16MHz, 3=20MHz (Turbo)
I2S_SPEED=2
# Refresco Minimo (Hz): 30 a 120
REFRESH_MIN=120
# Doble Buffer: 0=OFF, 1=ON (Elimina parpadeos)
DOUBLE_BUFF=0
# Anti-Ghosting: 1 a 4 (Sube si ves brillo fantasma)
LATCH_BLANK=1

[LOGIC]
# Modo de visualizacion: 0=GIFs, 1=Solo Reloj
PLAY_MODE=0
# Activa o desactiva la configuracion mediante la APP: 0=OFF, 1=ON (Requiere WiFi)
CONFI_APP_ENABLE=1
# Selecciona tu sistema Arcade: 0=OFF, 1=Batocera, 2=Recalbox, 3=ReplayOS
ARCADE_ENABLE=0
# Activa o desactiva el texto en scroll: 0=OFF, 1=ON (Requiere WiFi)
TEXT_ENABLE=1
# Activa o desactiva el reloj: 0=OFF, 1=ON (Requiere WiFi)
CLOCK_ENABLE=1
# Modo de reproduccion: 0=Secuencial, 1=Aleatorio
RANDOM_MODE=1
# Intervalo: Cada cuantos GIFs aparece el reloj
AUTO_CLOCK_INT=6
# Duracion: Cuantos segundos se muestra el reloj
CLOCK_DURATION=10
# Estilos: 0=Matrix, 1=Solid, 2=Rainbow, 3=Pulse, 4=Gradient
CLOCK_STYLE=2
# Activa la transicion del reloj a GIFs con una explosion de particulas : 0=OFF, 1=ON
TRANSITION_ENABLE=1
# Color del reloj (0= Blanco, 1=Rojo, 2=Verde, 3=Azul, 4=Amarillo, 5=Cian, 6=Magenta, 7=Naranja, 8=Rosa)
CLOCK_COLOR=4

[WEATHER]
# Activa el clima: 0=OFF, 1=ON (Requiere WiFi)
WEATHER_ENABLE=1
# Tu ciudad (Sin espacios, usa '+' si es necesario: Madrid,ES o Buenos+Aires,AR)
CITY=Navalmoral+de+la+Mata,ES
# Tu API Key gratuita de OpenWeatherMap
API_KEY=xxxxxxxxxxxxxxxxxxxxxxx
# Intervalo de actualizacion del clima en MINUTOS
WEATHER_INT=60
# Texto que se muestra encima del reloj
WEATHER_MSG=Game Room

[LANGUAGE]
# Indica el Idioma (Nombre del archivo sin .json: ES, EN, FR...)
LANGUAGE=ES

[IMAGEN_EXTERNA]
# Timeout sin frames para volver a GIFs (ms): 200 a 5000
IMAGE_TIMEOUT=1000

[IR_REMOTE]
# Códigos HEX del mando IR (NO hay que indicar nada los guardará automaticamente Retro Pixel LED)
BTN_ON=F20DFF00
BTN_OFF=E01FFF00
BTN_BRILLO_UP=F609FF00
BTN_BRILLO_DOWN=E21DFF00
BTN_MENU=EA15FF00
BTN_OK=ED12FF00
BTN_SUBIR=E41BFF00
BTN_BAJAR=B34CFF00

[REPLAY_OS]
# IP que tiene asignada ReplayOS
IP=192.168.1.101
# Token ReplayOS: SYSTEM > INFORMATION > NET CONTROL CODE
TOKEN=

[END]
